'use client'

import { useEffect, useState, useCallback, Fragment, useMemo } from 'react'
import { useLanguage } from '@/lib/LanguageContext'
import type { Invoice, ARSummary } from '@/lib/types'

// ─── Utility helpers ──────────────────────────────────────────────────────────

function formatRupiah(n: number): string {
  return 'Rp ' + Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.')
}

function todayDDMMYYYY(): string {
  const now = new Date()
  const d = String(now.getDate()).padStart(2, '0')
  const m = String(now.getMonth() + 1).padStart(2, '0')
  return `${d}/${m}/${now.getFullYear()}`
}

// Convert dd/mm/yyyy → yyyy-mm-dd for <input type="date">
function toInputDate(ddmmyyyy: string): string {
  if (!ddmmyyyy) return ''
  const parts = ddmmyyyy.split('/')
  if (parts.length !== 3) return ''
  return `${parts[2]}-${parts[1]}-${parts[0]}`
}

// Convert yyyy-mm-dd (from <input type="date">) → dd/mm/yyyy for storage
function fromInputDate(yyyymmdd: string): string {
  if (!yyyymmdd) return ''
  const parts = yyyymmdd.split('-')
  if (parts.length !== 3) return ''
  return `${parts[2]}/${parts[1]}/${parts[0]}`
}

function addDays(ddmmyyyy: string, days: number): string {
  const parts = ddmmyyyy.split('/')
  if (parts.length !== 3) return ''
  const [d, m, y] = parts.map(Number)
  const date = new Date(y, m - 1, d)
  date.setDate(date.getDate() + days)
  return `${String(date.getDate()).padStart(2, '0')}/${String(date.getMonth() + 1).padStart(2, '0')}/${date.getFullYear()}`
}

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
}

function parseDDMMYYYY(s: string): Date {
  if (!s) return new Date(0)
  const parts = s.split('/')
  if (parts.length !== 3) return new Date(0)
  const [d, m, y] = parts.map(Number)
  if (!d || !m || !y) return new Date(0)
  return new Date(y, m - 1, d)
}

// ─── Shared input style helpers ───────────────────────────────────────────────

const inputBase = 'w-full px-3 py-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white text-gray-900'

function inputClass(field: string, errors: Record<string, string>) {
  return `${inputBase} ${errors[field] ? 'border-red-400' : 'border-gray-300'}`
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function StatusBadge({ invoice }: { invoice: Invoice }) {
  const { t } = useLanguage()

  if (invoice.isOverdue) {
    return (
      <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-red-100 text-red-700">
        {t('status.overdue')}
      </span>
    )
  }

  const classes: Record<Invoice['status'], string> = {
    Unpaid:  'bg-red-100 text-red-700',
    Partial: 'bg-yellow-100 text-yellow-700',
    Paid:    'bg-green-100 text-green-700',
  }

  const labels: Record<Invoice['status'], string> = {
    Unpaid:  t('status.unpaid'),
    Partial: t('status.partial'),
    Paid:    t('status.paid'),
  }

  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${classes[invoice.status]}`}>
      {labels[invoice.status]}
    </span>
  )
}

function SkeletonRow() {
  return (
    <tr className="animate-pulse">
      {Array.from({ length: 9 }).map((_, i) => (
        <td key={i} className="px-4 py-3">
          <div className="h-4 bg-gray-200 rounded" style={{ width: `${60 + (i % 3) * 20}%` }} />
        </td>
      ))}
    </tr>
  )
}

// ─── Modals ───────────────────────────────────────────────────────────────────

interface AddInvoiceModalProps {
  onClose: () => void
  onSaved: () => void
}

function AddInvoiceModal({ onClose, onSaved }: AddInvoiceModalProps) {
  const { t } = useLanguage()
  const [form, setForm] = useState({
    invoiceCode: '', customerName: '', address: '', invoiceDate: toInputDate(todayDDMMYYYY()), dueDays: '30', discount: '0', totalAmount: '',
  })
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(true)
  const [loadingCode, setLoadingCode] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState('')

  useEffect(() => {
    if (!codeAutoGenerated) return
    const ddmmyyyy = fromInputDate(form.invoiceDate)
    if (!ddmmyyyy) return
    let cancelled = false
    setLoadingCode(true)
    fetch(`/api/receivables/next-code?date=${encodeURIComponent(ddmmyyyy)}`)
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => { if (!cancelled && data?.code) setForm((prev) => ({ ...prev, invoiceCode: data.code })) })
      .finally(() => { if (!cancelled) setLoadingCode(false) })
    return () => { cancelled = true }
  }, [form.invoiceDate, codeAutoGenerated])

  function validate() {
    const e: Record<string, string> = {}
    if (!form.invoiceCode.trim()) e.invoiceCode = t('ar.modal.addInvoice.code') + ' required'
    if (!form.customerName.trim()) e.customerName = t('ar.modal.addInvoice.customer') + ' required'
    if (!form.invoiceDate) e.invoiceDate = t('ar.modal.addInvoice.invoiceDate') + ' required'
    if (!form.dueDays || parseInt(form.dueDays) <= 0) e.dueDays = t('ar.modal.addInvoice.dueDays') + ' required'
    if (!form.totalAmount || parseFloat(form.totalAmount) <= 0) e.totalAmount = t('ar.modal.addInvoice.total') + ' required'
    return e
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const errs = validate()
    if (Object.keys(errs).length > 0) { setErrors(errs); return }
    setSaving(true)
    setSaveError('')
    try {
      const invoiceDate = fromInputDate(form.invoiceDate)
      const dueDate = addDays(invoiceDate, parseInt(form.dueDays))
      const res = await fetch('/api/receivables', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          invoiceCode: form.invoiceCode,
          customerName: form.customerName,
          address: form.address,
          discount: form.discount,
          invoiceDate,
          dueDate,
          totalAmount: form.totalAmount,
        }),
      })
      if (!res.ok) throw new Error()
      onSaved()
    } catch {
      setSaveError(t('ar.saveError'))
    } finally {
      setSaving(false)
    }
  }

  const invoiceDateDDMM = fromInputDate(form.invoiceDate)
  const computedDue = invoiceDateDDMM && parseInt(form.dueDays) > 0
    ? addDays(invoiceDateDDMM, parseInt(form.dueDays))
    : null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-lg">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <h2 className="text-base font-semibold text-gray-900">{t('ar.modal.addInvoice.title')}</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-xl leading-none">×</button>
        </div>
        <form onSubmit={handleSubmit} className="px-6 py-4 space-y-4">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.code')}</label>
            <input
              className={inputClass('invoiceCode', errors)}
              placeholder={loadingCode ? t('common.generating') : t('ar.modal.addInvoice.ph.code')}
              value={form.invoiceCode}
              onChange={(e) => { setCodeAutoGenerated(false); setForm({ ...form, invoiceCode: e.target.value }) }}
            />
            {errors.invoiceCode && <p className="text-xs text-red-500 mt-1">{errors.invoiceCode}</p>}
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.customer')}</label>
            <input
              className={inputClass('customerName', errors)}
              placeholder={t('ar.modal.addInvoice.ph.customer')}
              value={form.customerName}
              onChange={(e) => setForm({ ...form, customerName: e.target.value })}
            />
            {errors.customerName && <p className="text-xs text-red-500 mt-1">{errors.customerName}</p>}
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.address')}</label>
            <input
              className={inputClass('address', errors)}
              placeholder={t('ar.modal.addInvoice.ph.address')}
              value={form.address}
              onChange={(e) => setForm({ ...form, address: e.target.value })}
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.invoiceDate')}</label>
              <input
                type="date"
                className={inputClass('invoiceDate', errors)}
                value={form.invoiceDate}
                onChange={(e) => setForm({ ...form, invoiceDate: e.target.value })}
              />
              {errors.invoiceDate && <p className="text-xs text-red-500 mt-1">{errors.invoiceDate}</p>}
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.dueDays')}</label>
              <input
                type="number"
                min="1"
                className={inputClass('dueDays', errors)}
                placeholder={t('ar.modal.addInvoice.ph.dueDays')}
                value={form.dueDays}
                onChange={(e) => setForm({ ...form, dueDays: e.target.value })}
              />
              {errors.dueDays && <p className="text-xs text-red-500 mt-1">{errors.dueDays}</p>}
              {computedDue && (
                <p className="text-xs text-gray-400 mt-1">Due: {computedDue}</p>
              )}
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.total')}</label>
              <input
                type="number"
                min="1"
                className={inputClass('totalAmount', errors)}
                placeholder={t('ar.modal.addInvoice.ph.total')}
                value={form.totalAmount}
                onChange={(e) => setForm({ ...form, totalAmount: e.target.value })}
              />
              {errors.totalAmount && <p className="text-xs text-red-500 mt-1">{errors.totalAmount}</p>}
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.discount')}</label>
              <input
                type="number"
                min="0"
                max="100"
                className={inputClass('discount', errors)}
                placeholder={t('ar.modal.addInvoice.ph.discount')}
                value={form.discount}
                onChange={(e) => setForm({ ...form, discount: e.target.value })}
              />
            </div>
          </div>
          {saveError && <p className="text-sm text-red-600">{saveError}</p>}
          <div className="flex justify-end gap-3 pt-2">
            <button type="button" onClick={onClose} className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 transition-colors">
              {t('common.cancel')}
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 text-sm font-medium bg-blue-700 text-white rounded-lg hover:bg-blue-800 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
            >
              {saving ? t('common.saving') : t('common.save')}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

interface EditInvoiceModalProps {
  invoice: Invoice
  onClose: () => void
  onSaved: () => void
}

function EditInvoiceModal({ invoice, onClose, onSaved }: EditInvoiceModalProps) {
  const { t } = useLanguage()
  const [form, setForm] = useState({
    customerName: invoice.customerName,
    address: invoice.address,
    invoiceDate: toInputDate(invoice.invoiceDate),
    dueDate: toInputDate(invoice.dueDate),
    discount: invoice.discount || '0',
    totalAmount: invoice.totalAmount,
  })
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState('')

  function validate() {
    const e: Record<string, string> = {}
    if (!form.customerName.trim()) e.customerName = t('ar.modal.addInvoice.customer') + ' required'
    if (!form.invoiceDate) e.invoiceDate = t('ar.modal.addInvoice.invoiceDate') + ' required'
    if (!form.dueDate) e.dueDate = t('ar.modal.addInvoice.dueDate') + ' required'
    if (!form.totalAmount || parseFloat(form.totalAmount) <= 0) e.totalAmount = t('ar.modal.addInvoice.total') + ' required'
    return e
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const errs = validate()
    if (Object.keys(errs).length > 0) { setErrors(errs); return }
    setSaving(true)
    setSaveError('')
    try {
      const res = await fetch(`/api/receivables/${encodeURIComponent(invoice.invoiceCode)}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          customerName: form.customerName,
          address: form.address,
          invoiceDate: fromInputDate(form.invoiceDate),
          dueDate: fromInputDate(form.dueDate),
          discount: form.discount,
          totalAmount: form.totalAmount,
        }),
      })
      if (!res.ok) throw new Error()
      onSaved()
    } catch {
      setSaveError(t('ar.saveError'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-lg">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div>
            <h2 className="text-base font-semibold text-gray-900">{t('ar.modal.editInvoice.title')}</h2>
            <p className="text-xs text-gray-400 mt-0.5 font-mono">{invoice.invoiceCode}</p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-xl leading-none">×</button>
        </div>
        <form onSubmit={handleSubmit} className="px-6 py-4 space-y-4">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.customer')}</label>
            <input
              className={inputClass('customerName', errors)}
              value={form.customerName}
              onChange={(e) => setForm({ ...form, customerName: e.target.value })}
            />
            {errors.customerName && <p className="text-xs text-red-500 mt-1">{errors.customerName}</p>}
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.address')}</label>
            <input
              className={inputClass('address', errors)}
              placeholder={t('ar.modal.addInvoice.ph.address')}
              value={form.address}
              onChange={(e) => setForm({ ...form, address: e.target.value })}
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.invoiceDate')}</label>
              <input
                type="date"
                className={inputClass('invoiceDate', errors)}
                value={form.invoiceDate}
                onChange={(e) => setForm({ ...form, invoiceDate: e.target.value })}
              />
              {errors.invoiceDate && <p className="text-xs text-red-500 mt-1">{errors.invoiceDate}</p>}
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.dueDate')}</label>
              <input
                type="date"
                className={inputClass('dueDate', errors)}
                value={form.dueDate}
                onChange={(e) => setForm({ ...form, dueDate: e.target.value })}
              />
              {errors.dueDate && <p className="text-xs text-red-500 mt-1">{errors.dueDate}</p>}
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.total')}</label>
              <input
                type="number"
                min="1"
                className={inputClass('totalAmount', errors)}
                value={form.totalAmount}
                onChange={(e) => setForm({ ...form, totalAmount: e.target.value })}
              />
              {errors.totalAmount && <p className="text-xs text-red-500 mt-1">{errors.totalAmount}</p>}
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addInvoice.discount')}</label>
              <input
                type="number"
                min="0"
                max="100"
                className={inputClass('discount', errors)}
                placeholder={t('ar.modal.addInvoice.ph.discount')}
                value={form.discount}
                onChange={(e) => setForm({ ...form, discount: e.target.value })}
              />
            </div>
          </div>
          {saveError && <p className="text-sm text-red-600">{saveError}</p>}
          <div className="flex justify-end gap-3 pt-2">
            <button type="button" onClick={onClose} className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 transition-colors">
              {t('common.cancel')}
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 text-sm font-medium bg-blue-700 text-white rounded-lg hover:bg-blue-800 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
            >
              {saving ? t('common.saving') : t('common.save')}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

interface AddPaymentModalProps {
  invoiceCode: string
  onClose: () => void
  onSaved: () => void
}

function AddPaymentModal({ invoiceCode, onClose, onSaved }: AddPaymentModalProps) {
  const { t } = useLanguage()
  const [form, setForm] = useState({ paymentDate: toInputDate(todayDDMMYYYY()), amountPaid: '' })
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState('')

  function validate() {
    const e: Record<string, string> = {}
    if (!form.paymentDate) e.paymentDate = t('ar.modal.addPayment.date') + ' required'
    if (!form.amountPaid || parseFloat(form.amountPaid) <= 0) e.amountPaid = t('ar.modal.addPayment.amount') + ' required'
    return e
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const errs = validate()
    if (Object.keys(errs).length > 0) { setErrors(errs); return }
    setSaving(true)
    setSaveError('')
    try {
      const res = await fetch(`/api/receivables/${encodeURIComponent(invoiceCode)}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          paymentDate: fromInputDate(form.paymentDate),
          amountPaid: form.amountPaid,
        }),
      })
      if (!res.ok) throw new Error()
      onSaved()
    } catch {
      setSaveError(t('ar.saveError'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-md">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div>
            <h2 className="text-base font-semibold text-gray-900">{t('ar.modal.addPayment.title')}</h2>
            <p className="text-xs text-gray-500 mt-0.5">{t('ar.modal.addPayment.for')}: <span className="font-medium text-gray-700">{invoiceCode}</span></p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-xl leading-none">×</button>
        </div>
        <form onSubmit={handleSubmit} className="px-6 py-4 space-y-4">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addPayment.date')}</label>
            <input
              type="date"
              className={inputClass('paymentDate', errors)}
              value={form.paymentDate}
              onChange={(e) => setForm({ ...form, paymentDate: e.target.value })}
            />
            {errors.paymentDate && <p className="text-xs text-red-500 mt-1">{errors.paymentDate}</p>}
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">{t('ar.modal.addPayment.amount')}</label>
            <input
              type="number"
              min="1"
              className={inputClass('amountPaid', errors)}
              placeholder={t('ar.modal.addPayment.ph.amount')}
              value={form.amountPaid}
              onChange={(e) => setForm({ ...form, amountPaid: e.target.value })}
            />
            {errors.amountPaid && <p className="text-xs text-red-500 mt-1">{errors.amountPaid}</p>}
          </div>
          {saveError && <p className="text-sm text-red-600">{saveError}</p>}
          <div className="flex justify-end gap-3 pt-2">
            <button type="button" onClick={onClose} className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 transition-colors">
              {t('common.cancel')}
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 text-sm font-medium bg-blue-700 text-white rounded-lg hover:bg-blue-800 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
            >
              {saving ? t('common.saving') : t('common.save')}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

interface DeleteConfirmModalProps {
  invoice: Invoice
  isDeleting: boolean
  deleteError: string
  onClose: () => void
  onConfirm: () => void
}

function DeleteConfirmModal({ invoice, isDeleting, deleteError, onClose, onConfirm }: DeleteConfirmModalProps) {
  const { t } = useLanguage()

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-md">
        <div className="px-6 pt-5 pb-4">
          <h2 className="text-base font-semibold text-gray-900 mb-2">{t('ar.deleteInvoice')}</h2>
          <p className="text-sm text-gray-600 mb-2">{t('ar.confirmDelete')}</p>
          <p className="text-sm font-mono font-medium text-gray-800">
            {invoice.invoiceCode} — {invoice.customerName}
          </p>
          {deleteError && <p className="text-sm text-red-600 mt-3">{deleteError}</p>}
        </div>
        <div className="flex justify-end gap-3 px-6 pb-5">
          <button
            type="button"
            onClick={onClose}
            disabled={isDeleting}
            className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 transition-colors disabled:opacity-50"
          >
            {t('common.cancel')}
          </button>
          <button
            type="button"
            onClick={onConfirm}
            disabled={isDeleting}
            className="px-4 py-2 text-sm font-medium bg-red-600 text-white rounded-lg hover:bg-red-700 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
          >
            {isDeleting ? t('common.saving') : t('common.delete')}
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function ReceivablesPage() {
  const { t } = useLanguage()
  const [invoices, setInvoices] = useState<Invoice[]>([])
  const [summary, setSummary] = useState<ARSummary | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [lastSynced, setLastSynced] = useState<Date | null>(null)
  const [syncing, setSyncing] = useState(false)
  const [expandedRow, setExpandedRow] = useState<string | null>(null)
  const [showAddInvoice, setShowAddInvoice] = useState(false)
  const [showAddPayment, setShowAddPayment] = useState<string | null>(null)
  const [editingInvoice, setEditingInvoice] = useState<Invoice | null>(null)
  const [deletingInvoice, setDeletingInvoice] = useState<Invoice | null>(null)
  const [isDeleting, setIsDeleting] = useState(false)
  const [deleteError, setDeleteError] = useState('')

  // ─── Search & filter state ────────────────────────────────────────────────
  const [searchScope, setSearchScope] = useState<'all' | 'code' | 'customer'>('all')
  const [searchText, setSearchText] = useState('')
  const [showFilters, setShowFilters] = useState(false)
  const [filterStatuses, setFilterStatuses] = useState<Set<string>>(new Set())
  const [filterInvoiceMonth, setFilterInvoiceMonth] = useState('')
  const [filterDueMonth, setFilterDueMonth] = useState('')

  const activeFilterCount = filterStatuses.size + (filterInvoiceMonth ? 1 : 0) + (filterDueMonth ? 1 : 0)
  const hasActiveFilters = activeFilterCount > 0 || searchText.trim() !== ''

  // ─── Sort state ───────────────────────────────────────────────────────────
  const [sortColumn, setSortColumn] = useState<string | null>(null)
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc')

  function handleSort(col: string) {
    if (sortColumn === col) {
      if (sortDirection === 'asc') setSortDirection('desc')
      else { setSortColumn(null); setSortDirection('asc') }
    } else {
      setSortColumn(col)
      setSortDirection('asc')
    }
  }

  function sortIcon(col: string) {
    if (sortColumn !== col) return <span className="ml-1 text-gray-300">⇅</span>
    return sortDirection === 'asc'
      ? <span className="ml-1 text-blue-500">↑</span>
      : <span className="ml-1 text-blue-500">↓</span>
  }

  function resetAll() {
    setSearchText('')
    setSearchScope('all')
    setFilterStatuses(new Set())
    setFilterInvoiceMonth('')
    setFilterDueMonth('')
    setShowFilters(false)
  }

  function toggleStatus(s: string) {
    setFilterStatuses((prev) => {
      const next = new Set(prev)
      if (next.has(s)) next.delete(s); else next.add(s)
      return next
    })
  }

  const filteredInvoices = useMemo(() => {
    let result = invoices
    const q = searchText.trim().toLowerCase()
    if (q) {
      result = result.filter((inv) => {
        if (searchScope === 'code') return inv.invoiceCode.toLowerCase().includes(q)
        if (searchScope === 'customer') return inv.customerName.toLowerCase().includes(q)
        return (
          inv.invoiceCode.toLowerCase().includes(q) ||
          inv.customerName.toLowerCase().includes(q) ||
          inv.address.toLowerCase().includes(q) ||
          inv.invoiceDate.includes(q) ||
          inv.dueDate.includes(q)
        )
      })
    }
    if (filterStatuses.size > 0) {
      result = result.filter((inv) => {
        const effectiveStatus = inv.isOverdue ? 'Overdue' : inv.status
        return filterStatuses.has(effectiveStatus)
      })
    }
    if (filterInvoiceMonth) {
      const [fy, fm] = filterInvoiceMonth.split('-').map(Number)
      result = result.filter((inv) => {
        const invDate = parseDDMMYYYY(inv.invoiceDate)
        return invDate.getFullYear() === fy && invDate.getMonth() + 1 === fm
      })
    }
    if (filterDueMonth) {
      const [fy, fm] = filterDueMonth.split('-').map(Number)
      result = result.filter((inv) => {
        const dueDate = parseDDMMYYYY(inv.dueDate)
        return dueDate.getFullYear() === fy && dueDate.getMonth() + 1 === fm
      })
    }
    if (sortColumn) {
      result = [...result].sort((a, b) => {
        let valA: string | number = 0
        let valB: string | number = 0
        switch (sortColumn) {
          case 'invoiceCode':  valA = a.invoiceCode;  valB = b.invoiceCode;  break
          case 'customerName': valA = a.customerName; valB = b.customerName; break
          case 'invoiceDate':  valA = parseDDMMYYYY(a.invoiceDate).getTime(); valB = parseDDMMYYYY(b.invoiceDate).getTime(); break
          case 'dueDate':      valA = parseDDMMYYYY(a.dueDate).getTime();     valB = parseDDMMYYYY(b.dueDate).getTime();     break
          case 'netAmount':    valA = a.netAmount;    valB = b.netAmount;    break
          case 'remaining':    valA = a.remaining;    valB = b.remaining;    break
        }
        if (valA < valB) return sortDirection === 'asc' ? -1 : 1
        if (valA > valB) return sortDirection === 'asc' ? 1 : -1
        return 0
      })
    }
    return result
  }, [invoices, searchText, searchScope, filterStatuses, filterInvoiceMonth, filterDueMonth, sortColumn, sortDirection])

  const filteredSummary = useMemo(() => {
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    const in7Days = new Date(today)
    in7Days.setDate(in7Days.getDate() + 7)
    return {
      totalOutstanding: filteredInvoices
        .filter(inv => inv.status !== 'Paid')
        .reduce((sum, inv) => sum + inv.remaining, 0),
      overdueCount: filteredInvoices.filter(inv => inv.isOverdue).length,
      dueSoon7Days: filteredInvoices.filter(inv => {
        if (inv.status === 'Paid' || inv.isOverdue) return false
        const due = parseDDMMYYYY(inv.dueDate)
        return due >= today && due <= in7Days
      }).length,
    }
  }, [filteredInvoices])

  const fetchData = useCallback(async (isManual = false) => {
    if (isManual) setSyncing(true)
    try {
      const res = await fetch('/api/receivables')
      if (!res.ok) throw new Error()
      const data = await res.json()
      setInvoices(data.invoices)
      setSummary(data.summary)
      setError('')
      setLastSynced(new Date())
    } catch {
      setError(t('ar.error'))
    } finally {
      setLoading(false)
      setSyncing(false)
    }
  }, [t])

  useEffect(() => {
    fetchData()
    const interval = setInterval(() => fetchData(), 30_000)
    return () => clearInterval(interval)
  }, [fetchData])

  function handleSaved() {
    setShowAddInvoice(false)
    setShowAddPayment(null)
    setEditingInvoice(null)
    fetchData(true)
  }

  async function handleDeleteConfirm() {
    if (!deletingInvoice) return
    setIsDeleting(true)
    setDeleteError('')
    try {
      const res = await fetch(`/api/receivables/${encodeURIComponent(deletingInvoice.invoiceCode)}`, {
        method: 'DELETE',
      })
      if (!res.ok) throw new Error()
      setDeletingInvoice(null)
      fetchData(true)
    } catch {
      setDeleteError(t('ar.deleteError'))
    } finally {
      setIsDeleting(false)
    }
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Page header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{t('ar.title')}</h1>
          <p className="text-xs text-gray-400 mt-1">
            {t('common.lastSynced')}{' '}
            {lastSynced ? formatTime(lastSynced) : t('common.never')}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => fetchData(true)}
            disabled={syncing}
            className="px-3 py-1.5 text-sm border border-gray-300 rounded-lg text-gray-600 hover:border-blue-400 hover:text-blue-700 disabled:opacity-50 transition-colors"
          >
            {syncing ? t('common.syncing') : t('common.sync')}
          </button>
          <button
            onClick={() => setShowAddInvoice(true)}
            className="px-4 py-1.5 text-sm font-medium bg-blue-700 text-white rounded-lg hover:bg-blue-800 transition-colors"
          >
            + {t('ar.addInvoice')}
          </button>
        </div>
      </div>

      {/* Summary bar */}
      {summary && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
          <div className="bg-white rounded-xl border border-gray-200 p-4 shadow-sm">
            <p className="text-xs text-gray-500 mb-1">{t('ar.summary.outstanding')}</p>
            <p className="text-xl font-bold text-gray-900">{formatRupiah(filteredSummary.totalOutstanding)}</p>
            {hasActiveFilters && <p className="text-xs text-blue-500 mt-1">{filteredInvoices.length} / {invoices.length} invoices</p>}
          </div>
          <div className="bg-white rounded-xl border border-gray-200 p-4 shadow-sm">
            <p className="text-xs text-gray-500 mb-1">{t('ar.summary.overdue')}</p>
            <p className="text-xl font-bold text-red-600">{filteredSummary.overdueCount}</p>
            <p className="text-xs text-gray-400">{t('ar.summary.invoices')}</p>
          </div>
          <div className="bg-white rounded-xl border border-gray-200 p-4 shadow-sm">
            <p className="text-xs text-gray-500 mb-1">{t('ar.summary.dueSoon')}</p>
            <p className="text-xl font-bold text-yellow-600">{filteredSummary.dueSoon7Days}</p>
            <p className="text-xs text-gray-400">{t('ar.summary.invoices')}</p>
          </div>
        </div>
      )}

      {/* Search & filter bar */}
      <div className="mb-4 space-y-2">
        <div className="flex gap-2">
          <div className="flex flex-1 rounded-lg border border-gray-300 overflow-hidden focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-blue-500 bg-white">
            <select
              className="px-2 py-2 text-xs text-gray-600 bg-gray-50 border-r border-gray-300 focus:outline-none"
              value={searchScope}
              onChange={(e) => setSearchScope(e.target.value as 'all' | 'code' | 'customer')}
            >
              <option value="all">{t('common.allFields')}</option>
              <option value="code">{t('ar.col.invoiceCode')}</option>
              <option value="customer">{t('ar.col.customer')}</option>
            </select>
            <input
              className="flex-1 px-3 py-2 text-sm focus:outline-none bg-white"
              placeholder={t('common.search')}
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
            />
            {searchText && (
              <button onClick={() => setSearchText('')} className="px-3 text-gray-400 hover:text-gray-600 transition-colors">×</button>
            )}
          </div>
          <button
            onClick={() => setShowFilters(!showFilters)}
            className={`px-3 py-2 text-sm rounded-lg border transition-colors whitespace-nowrap ${
              showFilters || activeFilterCount > 0
                ? 'border-blue-500 text-blue-700 bg-blue-50'
                : 'border-gray-300 text-gray-600 hover:border-blue-400 hover:text-blue-700'
            }`}
          >
            {t('common.filter')}{activeFilterCount > 0 ? ` · ${activeFilterCount}` : ''}
          </button>
          {hasActiveFilters && (
            <button
              onClick={resetAll}
              className="px-3 py-2 text-sm rounded-lg border border-gray-300 text-gray-500 hover:text-red-600 hover:border-red-300 transition-colors whitespace-nowrap"
            >
              × {t('common.resetAll')}
            </button>
          )}
        </div>

        {showFilters && (
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-4 space-y-4">
            <div>
              <p className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">{t('common.status')}</p>
              <div className="flex flex-wrap gap-2">
                {(['Unpaid', 'Partial', 'Paid', 'Overdue'] as const).map((s) => (
                  <button
                    key={s}
                    onClick={() => toggleStatus(s)}
                    className={`px-3 py-1 text-xs rounded-full border transition-colors ${
                      filterStatuses.has(s)
                        ? 'bg-blue-700 text-white border-blue-700'
                        : 'border-gray-300 text-gray-600 hover:border-blue-400 hover:text-blue-700'
                    }`}
                  >
                    {s === 'Unpaid' ? t('status.unpaid') : s === 'Partial' ? t('status.partial') : s === 'Paid' ? t('status.paid') : t('status.overdue')}
                  </button>
                ))}
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">{t('ar.col.invoiceDate')}</p>
                <input
                  type="month"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={filterInvoiceMonth}
                  onChange={(e) => setFilterInvoiceMonth(e.target.value)}
                />
                {filterInvoiceMonth && (
                  <button onClick={() => setFilterInvoiceMonth('')} className="mt-1 text-xs text-gray-400 hover:text-red-500 transition-colors">× clear</button>
                )}
              </div>
              <div>
                <p className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">{t('ar.col.dueDate')}</p>
                <input
                  type="month"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={filterDueMonth}
                  onChange={(e) => setFilterDueMonth(e.target.value)}
                />
                {filterDueMonth && (
                  <button onClick={() => setFilterDueMonth('')} className="mt-1 text-xs text-gray-400 hover:text-red-500 transition-colors">× clear</button>
                )}
              </div>
            </div>
            <div className="flex justify-end pt-1 border-t border-gray-100">
              <button onClick={resetAll} className="text-xs text-gray-400 hover:text-red-600 transition-colors">
                {t('common.resetFilters')}
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        {error ? (
          <div className="flex items-center justify-center py-16 text-red-500 text-sm">{error}</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50">
                  <th onClick={() => handleSort('invoiceCode')}  className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide cursor-pointer select-none hover:text-gray-700">{t('ar.col.invoiceCode')}{sortIcon('invoiceCode')}</th>
                  <th onClick={() => handleSort('customerName')} className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide cursor-pointer select-none hover:text-gray-700">{t('ar.col.customer')}{sortIcon('customerName')}</th>
                  <th onClick={() => handleSort('invoiceDate')}  className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide cursor-pointer select-none hover:text-gray-700">{t('ar.col.invoiceDate')}{sortIcon('invoiceDate')}</th>
                  <th onClick={() => handleSort('dueDate')}      className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide cursor-pointer select-none hover:text-gray-700">{t('ar.col.dueDate')}{sortIcon('dueDate')}</th>
                  <th onClick={() => handleSort('netAmount')}    className="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide cursor-pointer select-none hover:text-gray-700">{t('ar.col.total')}{sortIcon('netAmount')}</th>
                  <th className="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">{t('ar.col.paid')}</th>
                  <th onClick={() => handleSort('remaining')}    className="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide cursor-pointer select-none hover:text-gray-700">{t('ar.col.remaining')}{sortIcon('remaining')}</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wide">{t('ar.col.status')}</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wide">{t('common.actions')}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {loading ? (
                  Array.from({ length: 4 }).map((_, i) => <SkeletonRow key={i} />)
                ) : filteredInvoices.length === 0 ? (
                  <tr>
                    <td colSpan={9} className="px-4 py-16 text-center text-sm text-gray-400">
                      {invoices.length === 0 ? (
                        t('ar.empty')
                      ) : (
                        <span>
                          {t('common.noResults')}{' '}
                          <button onClick={resetAll} className="text-blue-600 hover:underline">{t('common.resetAll')}</button>
                        </span>
                      )}
                    </td>
                  </tr>
                ) : (
                  filteredInvoices.map((invoice) => (
                    <Fragment key={invoice.invoiceCode}>
                      <tr
                        onClick={() => setExpandedRow(expandedRow === invoice.invoiceCode ? null : invoice.invoiceCode)}
                        className={`cursor-pointer transition-colors ${
                          invoice.isOverdue
                            ? 'bg-red-50/40 hover:bg-red-50'
                            : 'hover:bg-gray-50'
                        }`}
                      >
                        <td className={`px-4 py-3 font-mono text-xs font-medium ${invoice.isOverdue ? 'text-red-700 font-bold' : 'text-gray-900'}`}>
                          {invoice.invoiceCode}
                        </td>
                        <td className={`px-4 py-3 ${invoice.isOverdue ? 'text-red-700 font-bold' : 'text-gray-700'}`}>
                          {invoice.customerName}
                        </td>
                        <td className="px-4 py-3 text-gray-500 text-xs">{invoice.invoiceDate}</td>
                        <td className={`px-4 py-3 text-xs ${invoice.isOverdue ? 'text-red-600 font-semibold' : 'text-gray-500'}`}>
                          {invoice.dueDate}
                        </td>
                        <td className="px-4 py-3 text-right text-gray-700">
                          {formatRupiah(invoice.netAmount)}
                          {parseFloat(invoice.discount) > 0 && (
                            <span className="ml-1 text-xs text-gray-400">(-{invoice.discount}%)</span>
                          )}
                        </td>
                        <td className="px-4 py-3 text-right text-green-700">{formatRupiah(invoice.totalPaid)}</td>
                        <td className="px-4 py-3 text-right font-medium text-gray-900">{formatRupiah(invoice.remaining)}</td>
                        <td className="px-4 py-3 text-center">
                          <StatusBadge invoice={invoice} />
                        </td>
                        <td className="px-4 py-3" onClick={(e) => e.stopPropagation()}>
                          <div className="flex items-center gap-1 justify-center flex-wrap">
                            <button
                              onClick={() => setShowAddPayment(invoice.invoiceCode)}
                              className="px-2 py-1 text-xs font-medium bg-blue-50 text-blue-700 rounded hover:bg-blue-100 transition-colors whitespace-nowrap"
                            >
                              + {t('ar.addPayment')}
                            </button>
                            <button
                              onClick={() => setEditingInvoice(invoice)}
                              className="px-2 py-1 text-xs font-medium bg-gray-50 text-gray-700 rounded hover:bg-gray-100 transition-colors"
                            >
                              {t('common.edit')}
                            </button>
                            <button
                              onClick={() => { setDeleteError(''); setDeletingInvoice(invoice) }}
                              className="px-2 py-1 text-xs font-medium bg-red-50 text-red-700 rounded hover:bg-red-100 transition-colors"
                            >
                              {t('common.delete')}
                            </button>
                          </div>
                        </td>
                      </tr>

                      {expandedRow === invoice.invoiceCode && (
                        <tr className="bg-blue-50/30">
                          <td colSpan={9} className="px-6 py-4">
                            <div className="flex flex-wrap gap-6 mb-4 text-xs text-gray-500">
                              {invoice.address && (
                                <span><span className="font-medium text-gray-600">{t('ar.col.address')}:</span> {invoice.address}</span>
                              )}
                              <span><span className="font-medium text-gray-600">{t('ar.col.grossTotal')}:</span> {formatRupiah(parseFloat(invoice.totalAmount) || 0)}</span>
                              {parseFloat(invoice.discount) > 0 && (
                                <span><span className="font-medium text-gray-600">{t('ar.col.discount')}:</span> {invoice.discount}%</span>
                              )}
                            </div>
                            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
                              {t('ar.payments.title')}
                            </p>
                            {invoice.payments.length === 0 ? (
                              <p className="text-sm text-gray-400 italic">{t('ar.payments.none')}</p>
                            ) : (
                              <table className="w-full text-xs border border-gray-200 rounded-lg overflow-hidden">
                                <thead>
                                  <tr className="bg-gray-100">
                                    <th className="px-3 py-2 text-left text-gray-500 font-semibold">{t('ar.payments.date')}</th>
                                    <th className="px-3 py-2 text-right text-gray-500 font-semibold">{t('ar.payments.amount')}</th>
                                    <th className="px-3 py-2 text-center text-gray-500 font-semibold">{t('ar.payments.status')}</th>
                                  </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100 bg-white">
                                  {invoice.payments.map((p, i) => (
                                    <tr key={i}>
                                      <td className="px-3 py-2 text-gray-600">{p.paymentDate}</td>
                                      <td className="px-3 py-2 text-right font-medium text-green-700">{formatRupiah(p.amountPaid)}</td>
                                      <td className="px-3 py-2 text-center">
                                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                                          p.status === 'Paid'    ? 'bg-green-100 text-green-700' :
                                          p.status === 'Partial' ? 'bg-yellow-100 text-yellow-700' :
                                                                   'bg-red-100 text-red-700'
                                        }`}>
                                          {p.status === 'Paid'    ? t('status.paid') :
                                           p.status === 'Partial' ? t('status.partial') :
                                                                    t('status.unpaid')}
                                        </span>
                                      </td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            )}
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  ))
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {showAddInvoice && (
        <AddInvoiceModal onClose={() => setShowAddInvoice(false)} onSaved={handleSaved} />
      )}
      {showAddPayment && (
        <AddPaymentModal
          invoiceCode={showAddPayment}
          onClose={() => setShowAddPayment(null)}
          onSaved={handleSaved}
        />
      )}
      {editingInvoice && (
        <EditInvoiceModal
          invoice={editingInvoice}
          onClose={() => setEditingInvoice(null)}
          onSaved={handleSaved}
        />
      )}
      {deletingInvoice && (
        <DeleteConfirmModal
          invoice={deletingInvoice}
          isDeleting={isDeleting}
          deleteError={deleteError}
          onClose={() => setDeletingInvoice(null)}
          onConfirm={handleDeleteConfirm}
        />
      )}
    </div>
  )
}
